#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true

# default lists actions
default:
  @just -f justfile --list

service-run:
  #!/usr/bin/env bash
  set -eufo pipefail

  echo "*************************************"
  echo "** SERVICE-RUN"
  echo "*************************************"
  npm run docker:build
  npm run docker:run

tests-run:
  #!/usr/bin/env bash
  set -eufo pipefail

  echo "*************************************"
  echo "** TESTS-RUN"
  echo "*************************************"
  ENDPOINT=http://0.0.0.0:8000
  curl -vvv --parallel --parallel-immediate --parallel-max 10  ${ENDPOINT}/sleep/12 ${ENDPOINT}/sleep/12 ${ENDPOINT}/sleep/12 ${ENDPOINT}/sleep/12 ${ENDPOINT}/sleep/12 ${ENDPOINT}/sleep/12 ${ENDPOINT}/status/200 ${ENDPOINT}/status/200 ${ENDPOINT}/status/200

tests-run-simple:
  #!/usr/bin/env bash
  set -eufo pipefail

  echo "*************************************"
  echo "** TESTS-RUN-SIMPLE"
  echo "*************************************"
  ENDPOINT=http://0.0.0.0:8000
  curl -vvv ${ENDPOINT}/ping 

collector-run:
  #!/usr/bin/env bash
  set -eufo pipefail

  echo "*************************************"
  echo "** COLLECTOR-RUN"
  echo "*************************************"
  docker compose --env-file ./.env up -d --build --force-recreate

collector-stop:
  #!/usr/bin/env bash
  set -eufo pipefail

  echo "*************************************"
  echo "** COLLECTOR-STOP"
  echo "*************************************"
  docker compose --env-file ./.env down

collector-logs:
  #!/usr/bin/env bash
  set -eufo pipefail

  echo "*************************************"
  echo "** COLLECTOR-LOGS"
  echo "*************************************"
  #lnav docker://01_python_fastapi_tracing-collector-1          
  docker compose --env-file ./.env logs --follow

collector-restart: collector-stop collector-run collector-logs

local-test-pipeline:
  #!/usr/bin/env bash
  set -eufo pipefail

  echo "*************************************"
  echo "** Local pipeline"
  echo "*************************************"
  node --version
  #npm outdated
  #npm install
  #npm run lint
  #npm run test
  npm run start
  npm run docker:build
  npm run docker:run
  npm run docker:build:chainguard
  npm run docker:run:chainguard

test-all: local-test-pipeline

